# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    docker: 
      - image: gnradrian/java11-gradle7
    steps:
      - checkout
      - run: gradle build
      - run: gradle jar
      - run: gradle check
  
  test:
    docker: 
      - image: gnradrian/java11-gradle7
    steps:
     - checkout
     - run: gradle test
  
  validate:
    docker: 
      - image: gnradrian/java11-gradle7
    steps:
      - checkout
      - run: gradle check

  deploy:
    - heroku/deploy-via-git
        requires:
          - build
        filters:
          branches:
            only: master

workflows:
  version: 2
  tp4_scm_workflows:
    jobs:
      - build
      - test
      - validate
      - deploy