# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
   docker: 
     - image: gnradrian/java11-gradle7
   steps:
     - checkout
     - run: gradle build
     - run: gradle jar
     - run: gradle check
  
test:
  docker: 
     - image: gnradrian/java11-gradle7
  steps:
     - checkout
     - run: gradle test
  
validate:
  docker: 
     - image: gnradrian/java11-gradle7
  steps:
     - checkout
     - run: gradle check

#deploy:

workflows:
  version: 2
  tp4_scm_workflows:
    jobs:
      - build
      - test
      - validate
      #- deploy