# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk

    working_directory: ~/tp4-scm

    steps:
      - checkout
      - run: gradle clean
      - run: gradle build
      - run: gradle bootRun
  test:
    docker:
      - image: circleci/openjdk
    steps:
      - run: gradle test