# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    docker: 
      - image: gnradrian/java11-gradle7
    steps:
      - checkout
      - run: gradle build
      - run: gradle jar
      - run: gradle check
  
  test:
    docker: 
      - image: gnradrian/java11-gradle7
    steps:
     - checkout
     - run: gradle test
  
  validate:
    docker: 
      - image: gnradrian/java11-gradle7
    steps:
      - checkout
      - run: gradle check

  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git

workflows:
  version: 2
  tp4_scm_workflows:
    jobs:
      - validate
      - test:
          requires:
          - build
      - build:
          requires:
          - validate 
      - deploy:
          requires:
          - test